-- MySQL Script generated by MySQL Workbench
-- Wed Mar  5 18:13:55 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LogbuchDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LogbuchDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LogbuchDB` DEFAULT CHARACTER SET utf8 ;
USE `LogbuchDB` ;

-- -----------------------------------------------------
-- Table `LogbuchDB`.`Fahrzeugtyp_ID`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LogbuchDB`.`Fahrzeugtyp_ID` (
  `Fahrzeugtyp_ID` INT NOT NULL,
  `Typname` TEXT NULL,
  PRIMARY KEY (`Fahrzeugtyp_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LogbuchDB`.`Fahrten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LogbuchDB`.`Fahrten` (
  `Fahrten_ID` INT NOT NULL,
  `Datum ab` VARCHAR(45) NULL,
  `Datum bis` VARCHAR(45) NULL,
  `Gefahrene Kilometer` VARCHAR(45) NULL,
  `User_ID` TEXT NULL,
  `Fahrzeug_ID` TEXT NOT NULL,
  PRIMARY KEY (`Fahrten_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LogbuchDB`.`Fahrzeug`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LogbuchDB`.`Fahrzeug` (
  `Fahrzeug_ID` INT NOT NULL,
  `Marke` TEXT NULL,
  `Jahrgang` INT NULL,
  `Kilometerstand` VARCHAR(45) NULL,
  `Fahrzeugtyp-ID` INT NULL,
  `Kennzeichen` TEXT NULL,
  `Fahrzeugtyp_ID` INT NULL,
  `Fahrten_Fahrten_ID` INT NOT NULL,
  PRIMARY KEY (`Fahrzeug_ID`),
  INDEX `fk_Fahrzeug_Fahrzeugtyp_ID1_idx` (`Fahrzeugtyp_ID` ASC) VISIBLE,
  INDEX `fk_Fahrzeug_Fahrten1_idx` (`Fahrten_Fahrten_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Fahrzeug_Fahrzeugtyp_ID1`
    FOREIGN KEY (`Fahrzeugtyp_ID`)
    REFERENCES `LogbuchDB`.`Fahrzeugtyp_ID` (`Fahrzeugtyp_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fahrzeug_Fahrten1`
    FOREIGN KEY (`Fahrten_Fahrten_ID`)
    REFERENCES `LogbuchDB`.`Fahrten` (`Fahrten_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LogbuchDB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LogbuchDB`.`User` (
  `User_ID` INT NOT NULL,
  `Vorname` VARCHAR(45) NULL,
  `Nachname` VARCHAR(45) NULL,
  `Alter` VARCHAR(10) NULL,
  `Fahrzeug_ID` INT NOT NULL,
  PRIMARY KEY (`User_ID`),
  INDEX `fk_User_Fahrzeug_idx` (`Fahrzeug_ID` ASC) VISIBLE,
  CONSTRAINT `fk_User_Fahrzeug`
    FOREIGN KEY (`Fahrzeug_ID`)
    REFERENCES `LogbuchDB`.`Fahrzeug` (`Fahrzeug_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
